sudo: required

services:
  - docker

language: java
dist: bionic

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  - DOCKER_IMAGE=3978hge3gu/rso-music:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - dockerlogin -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "$DOCKER_IMAGE"
